dbfilename redis_queue.rdb
dir /Users/atulbhatt/Documents/Projects/Frappe-Erpnext/my-bench/config/pids
pidfile /Users/atulbhatt/Documents/Projects/Frappe-Erpnext/my-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /Users/atulbhatt/Documents/Projects/Frappe-Erpnext/my-bench/config/redis_queue.acl
